Rayku\RaykuStaticBundle\Form\FormType:
    properties:
        fullname:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Type: \email
        email1:
            - NotBlank: ~
            - Type: \email
        password:
            - NotBlank: ~
            Type: \password
        password1:
            - NotBlank: ~
            Type: \password
        confirm_password:
            - NotBlank: ~
            Type: \password