#
# more information can be found here http://sonata-project.org/bundles/user
#
fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Rayku\ApiBundle\Entity\User
    group:
        group_class: Application\Sonata\UserBundle\Entity\Group
    registration:
        form:
            type:   rayku_user_registration
