parameters:
    database_driver: pdo_mysql
    database_host: db1.p.rayku.com
    database_port: null
    database_name: rayku_db
    database_user: rayku_db
    database_password: UthmCRtaum34qpGL
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: bc095fe10e3c2ef9572aab951fd5bcf9c
    database_path: null
    wrapper_legacypath: legacy # directory inside app/ where your project is located
    wrapper_app: apps/frontend # app to load
    wrapper_env: prod #environment to load
    wrapper_debug: false #whether debug is on or not


