parameters:
    whiteboard_url:    http://whiteboard.rayku.local:8080

    database_driver:   pdo_mysql
    database_host:     localhost
    database_name:     rayku_v2
    database_user:     root
    database_password: abc123

    mailer_transport:   smtp
    mailer_host:        smtp.sendgrid.net
    mailer_user:        rayku
    mailer_password:    bghtyu123

    locale:             en

    secret:             faEHPFAWJIPEJPOEIJWF

    # Sonata Admin Options
    sonata_admin.title:             Rayku Admin
    sonata_admin.logo_title:        /bundles/sonataadmin/logo_title.png

    # Sonata Media options
    sonata_media.cdn.host:          /uploads/media

    # Sonata User Options
    sonata_user.google_authenticator.server:  demo.sonata-project.org
    
    rayku_referral.listener.kernel.query_param_name: refcode
    rayku_referral.listener.kernel.cookie_param_code: code
    rayku_referral.listener.kernel.cookie_param_ip: ip
    rayku_referral.listener.kernel.cookie_param_date: date
    rayku_referral.listener.kernel.cookie_param_referer: referrer
    rayku_referral.listener.kernel.reward_referrer: 200
    rayku_referral.listener.kernel.reward_referral: 500
    
    omni_pay.gateway.name: Stripe
    omni_pay.gateway.class: Omnipay\Stripe\Gateway

    payment.gateway.api_key: "sk_live_wD3nzHCxEqRo52mNKDjl2WsM"
    