rayku_page_import:
    resource: "@RaykuPageBundle/Controller"
    type:     annotation
    prefix:   /
    options:
        expose: true

rayku_api_import:
    resource: "@RaykuApiBundle/Resources/config/routing.yml"
    options:
        expose: true

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# Angular routes for the purpose of exporting them to fos js router
angular_dashboard:
    pattern: /#/dashboard
    options:
        expose: true

angular_profile:
    pattern: /#/profile
    options:
        expose: true

angular_settings:
    pattern: /#/settings
    options:
        expose: true

angular_payout:
    pattern: /#/payout
    options:
        expose: true

angular_course_view:
    pattern: /#/course/:name/view
    options:
        expose: true