security:
    acl:
        connection: default
    encoders:
        "FOS\UserBundle\Entity\User":
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # This firewall is used to handle the public login area
        # This part is handled by the FOS User Bundle
        main:
            pattern:      .*
            context:        user
            form_login:
                provider:       fos_userbundle
                login_path:     /
                use_forward:    false
                check_path:     /login_check
                failure_path:   /
                always_use_default_target_path: true
                default_target_path: /dashboard
            logout:       true
            anonymous:    true

    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Non-secure part of site
        - { path: ^/about$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/become-a-tutor$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        # Todo secure with HMAC
        - { path: ^/session, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secure rest of the site
        - { path: ^/, roles: ROLE_USER }
