security:
    acl:
        connection: default
    encoders:
        "FOS\UserBundle\Entity\User":
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            switch_user:        true
            context:            user
            pattern:            /admin(.*)
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
                use_referer:    true
            logout:
                path:           /admin/logout
                target:         /admin/login

            anonymous:    true
        main:
            switch_user: true
            jmikola_auto_login:
                auto_login_user_provider: rayku.auto_login_user_provider
                #token_param: al
            pattern:      .*
            context:        user
            form_login:
                provider:       fos_userbundle
                login_path:     /
                use_forward:    false
                check_path:     /login_check
                failure_path:   /
                always_use_default_target_path: true
                default_target_path: /dashboard
            logout:       true
            anonymous:    true

    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        # Admin secured areas
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/api, role: ROLE_ADMIN }

        # Non-secure part of site
        - { path: ^/ask$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fb$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/about$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/become-a-tutor$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/legal$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/tutor/.+/public, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        # Todo secure with HMAC
        - { path: ^/session, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secure rest of the site
        - { path: ^/, roles: ROLE_USER }
