_rayku_user_login:
    pattern:  /login
    defaults: { _controller: RaykuStaticBundle:Login:login }

_rayku_user_logout:
    pattern:  /logout
    defaults: { _controller: RaykuStaticBundle:Login:logout }

_rayku_user_register:
    pattern:  /register
    defaults: { _controller: RaykuStaticBundle:Registration:register }