rayku_session_rate:
    pattern: /session/{id}/rate
    defaults:
        _controller: RaykuPageBundle:Page:dashboard

rayku_page_homepage:
    pattern:  /
    defaults:
        _controller: RaykuPageBundle:Page:index
        
rayku_page_homepage_minimized_funnel:
    pattern:  /ask
    defaults:
        _controller: RaykuPageBundle:Page:index

rayku_register_confirmed:
    pattern: /register/confirmed
    defaults:
        _controller: RaykuPageBundle:Page:autoConnectSession

rayku_page_dashboard:
    pattern: /dashboard
    defaults: 
        _controller: RaykuPageBundle:Page:dashboard

rayku_page_about:
    pattern: /about
    defaults:
      _controller: FrameworkBundle:Template:template
      template: 'RaykuPageBundle:Page:about.html.twig'

rayku_page_tutor_onboarding:
    pattern: /onboarding
    defaults:
      _controller: FrameworkBundle:Template:template
      template: 'RaykuPageBundle:Page:onboarding.html.twig'

rayku_legal_page:
    pattern: /legal
    defaults:
      _controller: FrameworkBundle:Template:template
      template: 'RaykuPageBundle:Page:legal.html.twig'

rayku_page_become_a_tutor:
    pattern: /become-a-tutor
    defaults: 
        _controller: RaykuPageBundle:Page:become