rayku_user_rest:
    resource: Rayku\ApiBundle\Controller\UserController
    type:     rest

rayku_tutor_rest:
    resource: Rayku\ApiBundle\Controller\TutorController
    type:     rest

rayku_session_rest:
    resource: Rayku\ApiBundle\Controller\SessionController
    type:     rest

rayku_order_rest:
    resource: Rayku\ApiBundle\Controller\OrderController
    type:     rest

rayku_favorite_rest:
    resource: Rayku\ApiBundle\Controller\FavoriteController
    type:     rest

rayku_message_rest:
    resource: Rayku\ApiBundle\Controller\MessageController
    type:     rest
    